# tooling_lists.py

import re

def _normalize_tooling_list(items, list_name=""):
    """
    Return a new list where each item has:
      - clean strings for 'Item Number' / 'Item Name' / 'Category' (trimmed)
      - integer 'Quantity' (first integer found in the original value; default 1)
    """
    def _to_int(q):
        if isinstance(q, (int, float)):
            try:
                return max(int(q), 1)
            except Exception:
                return 1
        s = str(q or "").strip()
        m = re.search(r"\d+", s)
        return int(m.group(0)) if m else 1

    out = []
    for raw in items or []:
        out.append({
            "Item Number": str(raw.get("Item Number") or "").strip(),
            "Item Name":   str(raw.get("Item Name")   or "").strip(),
            "Quantity":    _to_int(raw.get("Quantity")),
            "Category":    str(raw.get("Category")    or "General").strip(),
        })
    return out


standard_trailer_tools = [{'Item Name': 'Venilation Fan', 'Item Number': 'S Air Movr', 'Quantity': 1, 'Category': 'AIR'}, {'Item Name': 'Whip Checks', 'Item Number': 'S WHP CHK', 'Quantity': 10, 'Category': 'AIR'}, {'Item Name': 'Chicago Air Hose', 'Item Number': 'PT 713-20665550', 'Quantity': 10, 'Category': 'AIR'}, {'Item Name': 'Husky Air Fittings', 'Item Number': 'Fillers', 'Quantity': 5, 'Category': 'AIR'}, {'Item Name': 'Saftey Pins for Air Hose', 'Item Number': 'PT Chgo Clip', 'Quantity': 5, 'Category': 'AIR'}, {'Item Name': 'Air Zip Gun', 'Item Number': 'PT Air zip gun', 'Quantity': 2, 'Category': 'AIR'}, {'Item Name': 'Chicago Y Fitting', 'Item Number': 'PT 3-way chic', 'Quantity': 1, 'Category': 'AIR'}, {'Item Name': 'Chicago Ball Valve', 'Item Number': 'PT Bll vlve 1-2', 'Quantity': 1, 'Category': 'AIR'}, {'Item Name': 'Chicago Grommets', 'Item Number': 'pt chgo grmt', 'Quantity': 5, 'Category': 'AIR'}, {'Item Name': 'Rivet Buster', 'Item Number': 'PT Rivit Bstr', 'Quantity': 1, 'Category': 'AIR'}, {'Item Name': 'Chisel Bit for Rivet Buster', 'Item Number': 'PT L02h12', 'Quantity': 1, 'Category': 'AIR'}, {'Item Name': 'Pointed bit for Rivet Buster', 'Item Number': 'PT l03h12', 'Quantity': 1, 'Category': 'AIR'}, {'Item Name': 'Needle Gun', 'Item Number': 'PT 4005', 'Quantity': 2, 'Category': 'AIR'}, {'Item Name': '1/4 AIRARC ROD 50 PER BOX', 'Item Number': 'w 22-043-003', 'Quantity': 2, 'Category': 'AIR'}, {'Item Name': '3/8 AIRARC ROD 50 PER BOX', 'Item Number': 'W 22-063-003', 'Quantity': 4, 'Category': 'AIR'}, {'Item Name': 'AIR ARC GOUGING GUN', 'Item Number': 'C 61-082-006', 'Quantity': 2, 'Category': 'AIR'}, {'Item Name': '100 WATT LIGHT BULBS', 'Item Number': 'EL 1002 109 690', 'Quantity': 4, 'Category': 'Electrical'}, {'Item Name': '110V 12/3 3-WAY GROUND FAULT INERRUPTER', 'Item Number': 'EL 04-00105', 'Quantity': 10, 'Category': 'Electrical'}, {'Item Name': "110V 12/3 EXTENSION CORD 50'", 'Item Number': 'EL 74050PK2V2', 'Quantity': 15, 'Category': 'Electrical'}, {'Item Name': '110V DROP LIGHT 100W RS BULB', 'Item Number': 'EL 542 246', 'Quantity': 5, 'Category': 'Electrical'}, {'Item Name': 'PORTABLE HALOGEN WORKLIGHT', 'Item Number': 'EL 1001 863 376', 'Quantity': 2, 'Category': 'Electrical'}, {'Item Name': '10" C-CLAMPS', 'Item Number': 'FT 410P', 'Quantity': 4, 'Category': 'Fitting'}, {'Item Name': '12 "ADJUSTABLE L-CLAMPS', 'Item Number': 'FT UM125', 'Quantity': 4, 'Category': 'Fitting'}, {'Item Name': 'COWBOY CLAMPS', 'Item Number': 'F CBY CLMP', 'Quantity': 4, 'Category': 'Fitting'}, {'Item Name': "LARGE LEVEL (OVER 6')", 'Item Number': 'FT 71.78', 'Quantity': 1, 'Category': 'Fitting'}, {'Item Name': 'LEVEL 4FT', 'Item Number': 'FT 75.48', 'Quantity': 2, 'Category': 'Fitting'}, {'Item Name': 'LEVEL 2FT', 'Item Number': 'FT 75.24', 'Quantity': 2, 'Category': 'Fitting'}, {'Item Name': 'PORTA POWER PUMPS AND CLYINDER', 'Item Number': 'HT B65115', 'Quantity': 1, 'Category': 'Fitting'}, {'Item Name': '"V" HEAD PIPE STAND', 'Item Number': 'FT 4100 PIPE STND', 'Quantity': 4, 'Category': 'Fitting'}, {'Item Name': '2-CYCLE OIL, QUART', 'Item Number': 'FL 2 CYCL OIL', 'Quantity': 2, 'Category': 'Flam_Cabinet'}, {'Item Name': 'TUBE OF GREASE', 'Item Number': 'FL 75-600', 'Quantity': 2, 'Category': 'Flam_Cabinet'}, {'Item Name': 'AIR TOOL OIL', 'Item Number': 'FL 383732', 'Quantity': 1, 'Category': 'Flam_Cabinet'}, {'Item Name': 'CUTTING OIL (1 GALLON)', 'Item Number': 'FL 30203', 'Quantity': 1, 'Category': 'Flam_Cabinet'}, {'Item Name': 'GREASE GUN', 'Item Number': 'HT 715-1230', 'Quantity': 1, 'Category': 'Flam_Cabinet'}, {'Item Name': 'HYDRAULIC FLUID, 1 QUART', 'Item Number': 'FL HYD FL \n', 'Quantity': 1, 'Category': 'Flam_Cabinet'}, {'Item Name': 'MOTOR OIL, 10W-40, QUART', 'Item Number': 'FL OIL 10w-40', 'Quantity': 2, 'Category': 'Flam_Cabinet'}, {'Item Name': 'PENETRATING OIL, SPRAY', 'Item Number': 'FL 1673', 'Quantity': 2, 'Category': 'Flam_Cabinet'}, {'Item Name': 'FLAPPER WHEEL', 'Item Number': 'GC 76318', 'Quantity': 20, 'Category': 'Grinding_Consumables'}, {'Item Name': '4" STRINGER BEAD WIRE WHEEL CS', 'Item Number': 'GC R4K58', 'Quantity': 10, 'Category': 'Grinding_Consumables'}, {'Item Name': '6" Cutting disc', 'Item Number': 'GC 22047', 'Quantity': 200, 'Category': 'Grinding_Consumables'}, {'Item Name': '4.5" GRINDING DISC', 'Item Number': 'GC 20160', 'Quantity': 40, 'Category': 'Grinding_Consumables'}, {'Item Name': '4" MASON GRINDING DIAMOND CUP', 'Item Number': 'GC AWD40', 'Quantity': 2, 'Category': 'Grinding_Consumables'}, {'Item Name': 'PIPE WRENCH 36"', 'Item Number': 'HT 36IN PIPE WR', 'Quantity': 1, 'Category': 'Hammer_Rack'}, {'Item Name': 'BOLT CUTTERS, 24" X 3/8"', 'Item Number': 'HT BLT CTTRS', 'Quantity': 1, 'Category': 'Hammer_Rack'}, {'Item Name': 'RD SHOVEL, LONG OR SHORT', 'Item Number': 'HT 1554300', 'Quantity': 1, 'Category': 'Hammer_Rack'}, {'Item Name': 'SQ SHOVEL, LONG OR SHORT', 'Item Number': 'HT 618004', 'Quantity': 1, 'Category': 'Hammer_Rack'}, {'Item Name': 'SLEAVER BAR', 'Item Number': 'FT 7168', 'Quantity': 6, 'Category': 'Hammer_Rack'}, {'Item Name': 'MILL BAR', 'Item Number': 'HT 1000 014 755', 'Quantity': 1, 'Category': 'Hammer_Rack'}, {'Item Name': 'FRAMING SQUARE', 'Item Number': 'FT 1110', 'Quantity': 2, 'Category': 'Hammer_Rack'}, {'Item Name': 'CHIPPING HAMMER', 'Item Number': 'HT WH-30', 'Quantity': 5, 'Category': 'Hammer_Rack'}, {'Item Name': 'CLAW HAMMER', 'Item Number': 'HT 1000 300 224', 'Quantity': 1, 'Category': 'Hammer_Rack'}, {'Item Name': 'DEAD BLOW HAMMER 4LB', 'Item Number': 'HT DEAD BLW 4LB', 'Quantity': 1, 'Category': 'Hammer_Rack'}, {'Item Name': 'HEAVY HAMMER 4LB', 'Item Number': 'HT 4LB', 'Quantity': 6, 'Category': 'Hammer_Rack'}, {'Item Name': 'HEAVY HAMMER 10#', 'Item Number': 'HT 10LB', 'Quantity': 2, 'Category': 'Hammer_Rack'}, {'Item Name': 'BROOM, PUSH', 'Item Number': 'HK 00528', 'Quantity': 1, 'Category': 'Hammer_Rack'}, {'Item Name': '5 Gallon Buckets', 'Item Number': 'HT HD BCKT', 'Quantity': 5, 'Category': 'House_keeping'}, {'Item Name': 'BLANK TAGS', 'Item Number': 'Saftey', 'Quantity': 15, 'Category': 'House_keeping'}, {'Item Name': 'ICE MELT (ONLY IF IN SEASON)', 'Item Number': 'Melt', 'Quantity': 1, 'Category': 'House_keeping'}, {'Item Name': 'TRASH CAN w/ LIDS', 'Item Number': 'HK 1926946', 'Quantity': 1, 'Category': 'House_keeping'}, {'Item Name': 'TRASH BAGS 55 GAL.', 'Item Number': 'HK 960 362', 'Quantity': 1, 'Category': 'House_keeping'}, {'Item Name': '2 WHEEL HAND TRUCK', 'Item Number': 'HT HD800P', 'Quantity': 1, 'Category': 'House_keeping'}, {'Item Name': 'CAULKING GUN', 'Item Number': 'HT HD109D', 'Quantity': 2, 'Category': 'House_keeping'}, {'Item Name': 'BOTTLE JACK', 'Item Number': 'HT 20TON BTL JCK \n', 'Quantity': 2, 'Category': 'House_keeping'}, {'Item Name': 'FLARE CARDS', 'Item Number': 'Flare', 'Quantity': 30, 'Category': 'House_keeping'}, {'Item Name': 'TIE WIRE (16 GAUGE)', 'Item Number': 'HT 05337', 'Quantity': 2, 'Category': 'House_keeping'}, {'Item Name': 'HAND CLEANER WIPES BUCKET', 'Item Number': 'S GOJO LRG', 'Quantity': 1, 'Category': 'House_keeping'}, {'Item Name': 'EXTENSION LADDER', 'Item Number': 'S EXT LDDR 24FT', 'Quantity': 1, 'Category': 'Ladder'}, {'Item Name': "STEP LADDER 8'", 'Item Number': 'S AFRAME 8FT', 'Quantity': 1, 'Category': 'Ladder'}, {'Item Name': '1/2" DRILL MOTOR', 'Item Number': 'PT DW511', 'Quantity': 2, 'Category': 'Power_Tools'}, {'Item Name': '1/2" IMPACT WRENCH', 'Item Number': 'PT 1-2IMPACT', 'Quantity': 4, 'Category': 'Power_Tools'}, {'Item Name': '3/4" IMPACT WRENCH', 'Item Number': 'PT DW294', 'Quantity': 1, 'Category': 'Power_Tools'}, {'Item Name': 'SDS HAMMER DRILL', 'Item Number': 'PT HMMRDRLL SDSMAX', 'Quantity': 1, 'Category': 'Power_Tools'}, {'Item Name': '1/2" MAGNETIC DRILL PRESS', 'Item Number': 'PT MAG DRLL', 'Quantity': 1, 'Category': 'Power_Tools'}, {'Item Name': 'DIE GRINDER', 'Item Number': 'PT DIE GRNDR', 'Quantity': 2, 'Category': 'Power_Tools'}, {'Item Name': '4-1/2" ANGLE GRINDER', 'Item Number': 'PT DWE402', 'Quantity': 6, 'Category': 'Power_Tools'}, {'Item Name': '6" ANGLE GRINDER (Metabo)', 'Item Number': 'PT WEP 15-150', 'Quantity': 6, 'Category': 'Power_Tools'}, {'Item Name': '9" ANGLE GRINDER', 'Item Number': 'PT GA9031Y', 'Quantity': 1, 'Category': 'Power_Tools'}, {'Item Name': '7-1/4" CIRCULAR SAW 110V', 'Item Number': 'PT 3204', 'Quantity': 1, 'Category': 'Power_Tools'}, {'Item Name': 'PORTABLE BAND SAW 110V 6 AMPS', 'Item Number': 'PT BND SW', 'Quantity': 1, 'Category': 'Power_Tools'}, {'Item Name': 'PORTABLE BAND SAW BLADES', 'Item Number': 'C 48 39 0524', 'Quantity': 1, 'Category': 'Power_Tools'}, {'Item Name': 'SAWSALL 110V 13AMPS', 'Item Number': 'PT SWZALL', 'Quantity': 1, 'Category': 'Power_Tools'}, {'Item Name': 'SAWSALL BLADE 6" Package', 'Item Number': 'PT 48 00 5093', 'Quantity': 1, 'Category': 'Power_Tools'}, {'Item Name': '100ft 3/8" cable', 'Item Number': 'RG 38-G CABLE', 'Quantity': 1, 'Category': 'Rigging'}, {'Item Name': '3/8" CROSBY CLAMPS', 'Item Number': 'Crosby', 'Quantity': 15, 'Category': 'Rigging'}, {'Item Name': '3/4 TON, CHAIN COME-A-LONGS', 'Item Number': 'RG LH34T', 'Quantity': 6, 'Category': 'Rigging'}, {'Item Name': '1 1/2 TON, CHAIN COME-A-LONGS', 'Item Number': 'RG LH15T', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': '3 TON, CHAIN COME-A-LONGS', 'Item Number': 'RG LH3T', 'Quantity': 2, 'Category': 'Rigging'}, {'Item Name': '1 TON, LIFT CHAIN X PULL CHAIN', 'Item Number': 'RG CF1T', 'Quantity': 6, 'Category': 'Rigging'}, {'Item Name': '2 TON, LIFT CHAIN X PULL CHAIN', 'Item Number': 'RG CF2T', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': '3 TON, LIFT CHAIN X PULL CHAIN', 'Item Number': 'RG CF3T', 'Quantity': 2, 'Category': 'Rigging'}, {'Item Name': '3/8" X 4\' CHOKER', 'Item Number': 'RG CC 38-4', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': '1/2" X 20\' CHOKER', 'Item Number': 'RG CC 12-20', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': '1/2" X 10\' CHOKER', 'Item Number': 'RG CC 12-10', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': '3/4" X 20\' CHOKER', 'Item Number': 'RG CC 34-20', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': '3/4" X 10\' CHOKER', 'Item Number': 'RG CC 34-10', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'BEAM CLAMP, 2 TON', 'Item Number': 'RG 2TBMCLMP', 'Quantity': 2, 'Category': 'Rigging'}, {'Item Name': 'SHACKLES 1/2"', 'Item Number': 'RG SHCKL 1-2', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'SHACKLES 5/8"', 'Item Number': 'RG SHCKL 5-8', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'SHACKLES 3/4"', 'Item Number': 'RG SHCKL 3-4', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'SHACKLES 7/8"', 'Item Number': 'RG SHCKL 7-8', 'Quantity': 6, 'Category': 'Rigging'}, {'Item Name': 'SHACKLES 1"', 'Item Number': 'RG SHCKL 1', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'SHACKLES 1-1/4"', 'Item Number': 'RG SHCKL 1-1/4', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'SNATCH (LIFT) BLOCK, 2-5 TON', 'Item Number': 'RG SNTCH BLK 418', 'Quantity': 2, 'Category': 'Rigging'}, {'Item Name': 'ROPE FOR TAGLINE', 'Item Number': 'HT 195522', 'Quantity': 1, 'Category': 'Rigging'}, {'Item Name': 'YELLOW 10FT', 'Item Number': 'RG YLLW 10FT', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'YELLOW 20FT', 'Item Number': 'RG YLLW 20FT', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'RED 10FT', 'Item Number': 'RG RED 10FT', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'RED 20FT', 'Item Number': 'RG RED 20FT', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'GREEN 6FT', 'Item Number': 'RG GRN 6FT', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': '2" X 4FT FLAT STRAP', 'Item Number': 'RG STRP 2-4', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': '1" X 4FT FLAT STRAP', 'Item Number': 'RG STRP 1-4', 'Quantity': 4, 'Category': 'Rigging'}, {'Item Name': 'SUSPENSION TRAUMA SAFETY STRAP', 'Item Number': 'S 9501403', 'Quantity': '4', 'Category': 'Rigging'}, {'Item Name': 'WHEEL CHOCKS', 'Item Number': 'S UC1700', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': 'VEHICHLE PRE OP BOOK', 'Item Number': 'S VEH PREOP', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': 'EQUIPMENT PRE OP BOOK', 'Item Number': 'S EQ PREOP', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': 'FOOT GAURDS', 'Item Number': 'S SHOE GRD', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': 'Ice Cleats', 'Item Number': 'S ICE CLT', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': 'CLEAR FACESHIELD', 'Item Number': 'PPE WM801000', 'Quantity': 40, 'Category': 'Saftey '}, {'Item Name': 'DARK FACESHIELD', 'Item Number': 'PPE WM858150', 'Quantity': 15, 'Category': 'Saftey '}, {'Item Name': 'SAFETY GLASSES CLEAR', 'Item Number': 'PPE 4110S', 'Quantity': 24, 'Category': 'Saftey '}, {'Item Name': 'GOGGLES, CLEAR LENS', 'Item Number': 'PPE 932-1', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': 'GLOVES SMALL', 'Item Number': 'PPE 3200BS S', 'Quantity': 24, 'Category': 'Saftey '}, {'Item Name': 'GLOVES MEDIUM', 'Item Number': 'PPE 3200BS M', 'Quantity': 24, 'Category': 'Saftey '}, {'Item Name': 'GLOVES LARGE', 'Item Number': 'PPE 3200BS L', 'Quantity': 24, 'Category': 'Saftey '}, {'Item Name': 'GLOVES X-LARGE', 'Item Number': 'PPE 3200BS XL', 'Quantity': 12, 'Category': 'Saftey '}, {'Item Name': 'WELDING GLOVES', 'Item Number': 'PPE 320L', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': 'L-LATEX GLOVES', 'Item Number': 'PPE 7MIL GLV', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'EAR PLUG REFILL', 'Item Number': 'PPE 6800', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'HARD HAT', 'Item Number': 'PPE E-2RW BLACK', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'Halo', 'Item Number': 'W SPEEDY-LOOP M5000', 'Quantity': 10, 'Category': 'Saftey '}, {'Item Name': 'DISPOSABLE DUST RESP. WELDING', 'Item Number': 'PPE 8210', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'RESPIRATOR CARTRIDGES MILLER', 'Item Number': 'PPE SA00818', 'Quantity': 10, 'Category': 'Saftey '}, {'Item Name': 'RESPIRATORY 1/2 MASK L MILLER', 'Item Number': 'PPE ML00895', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': 'RESPIRATORY WIPES', 'Item Number': 'PPE 1001', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'ZIPLOC BAGS 1 GALLON', 'Item Number': 'HK ZIPLC 1GAL', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'SAFETY VEST - LARGE', 'Item Number': 'PPE 6691UL', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': 'SAFETY VEST XL', 'Item Number': 'PPE 6691UXL', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': 'TYVEK COVERALL 3XL W/HOOD & BO', 'Item Number': 'PPE TY127S-3XL', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'SRL LANYARD', 'Item Number': 'PPE SRL LNYRD', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': '6ft tie off cheater', 'Item Number': 'PPE 96426RR', 'Quantity': 6, 'Category': 'Saftey '}, {'Item Name': 'FULL BODY HARNESS MD/LG', 'Item Number': 'PPE 01705A', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': "YO YO 30'", 'Item Number': 'S 30FT YOYO', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': 'ORANGE TRAFFIC CONES', 'Item Number': 'S TRFFC CN 18IN', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': '"CAUTION" BARRICADE TAPE (YELLOW)', 'Item Number': 'S 77-1001', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': '"DANGER" BARRICADE TAPE (RED)', 'Item Number': 'S 77-1004', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': 'PADLOCKS WITH KEYS (LOCK OUT LOCKS)', 'Item Number': 'S A1107BLUKD', 'Quantity': 12, 'Category': 'Saftey '}, {'Item Name': 'LOCKOUT BOX', 'Item Number': 'BOX', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'LOCK-OUT HASPS', 'Item Number': 'S ML420', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': 'CASES OF WATER', 'Item Number': 'S 782796', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': 'DUCT TAPE', 'Item Number': 'HT 1528195', 'Quantity': 4, 'Category': 'Saftey '}, {'Item Name': 'EYE WASH BOTTLES', 'Item Number': 'S 452', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': 'FIRE EXTINGUISHER TAG', 'Item Number': 'FIRE', 'Quantity': 3, 'Category': 'Saftey '}, {'Item Name': 'FIRE EXTINGUISHER BREAK AWAY TIE', 'Item Number': 'FIRE2', 'Quantity': 3, 'Category': 'Saftey '}, {'Item Name': 'FIRE EXTINGUISHER PIN', 'Item Number': 'FIRE3', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': 'FIRE EXTINGUISHER, 20# ABC (Must be insp. And tagged)', 'Item Number': 'FIRE4', 'Quantity': 6, 'Category': 'Saftey '}, {'Item Name': 'FIRST AID KIT, LARGE (Check Expiration)', 'Item Number': 'S 91339 \n', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'SEASONAL INSPECTION TAPE', 'Item Number': 'TAPE', 'Quantity': 2, 'Category': 'Saftey '}, {'Item Name': 'OIL SPILL CONTAINMENT KIT', 'Item Number': 'S OIL SPLL KIT', 'Quantity': 1, 'Category': 'Saftey '}, {'Item Name': 'LOCK OUT TAGS', 'Item Number': 'S 22CN05', 'Quantity': 24, 'Category': 'Saftey '}, {'Item Name': 'BARRICADE TAGS', 'Item Number': 'S TAR128', 'Quantity': 24, 'Category': 'Saftey '}, {'Item Name': '1/2" DRIVE SOCKET SET', 'Item Number': 'HT 13P 1/2 SKT', 'Quantity': 4, 'Category': 'Sockets'}, {'Item Name': '3/4" DRIVE SOCKET SET', 'Item Number': 'HT 3-4 SCKT ST', 'Quantity': 1, 'Category': 'Sockets'}, {'Item Name': '3/8" DRIVE SOCKET SET STD AND METRIC', 'Item Number': 'HT 21P 3/8 SKT \n', 'Quantity': 2, 'Category': 'Sockets'}, {'Item Name': 'HEX HEAD SOCKET SET STANDARD', 'Item Number': 'HT HX SCKT ST SAE', 'Quantity': 1, 'Category': 'Sockets'}, {'Item Name': 'HEX HEAD SOCKET SET METRIC', 'Item Number': 'HT HX SCKT ST METRIC', 'Quantity': 1, 'Category': 'Sockets'}, {'Item Name': 'METAL AMMO CAN FOR 1/2" SOCKET SETS', 'Item Number': 'HT MT AMO BX', 'Quantity': 5, 'Category': 'Sockets'}, {'Item Name': 'PLASTIC AMMO CAN FOR 3/8 AND HEX SETS', 'Item Number': 'HT PL AMO BX', 'Quantity': 3, 'Category': 'Sockets'}, {'Item Name': 'METRIC 1/2 INCH SOCKET SET', 'Item Number': 'HT MTRC 1-2 SCKT ST', 'Quantity': 1, 'Category': 'Sockets'}, {'Item Name': '3/8" RATCHET FOR SOCKET AND HEX SETS', 'Item Number': 'HT 3/8 RTCHT', 'Quantity': 3, 'Category': 'Sockets'}, {'Item Name': '1/2" RATCHETS FOR SOCKET SETS', 'Item Number': 'HT 1/2 Rtcht', 'Quantity': 5, 'Category': 'Sockets'}, {'Item Name': '4PC 1/2" SOCKET EXTENSIONS', 'Item Number': 'HT 4P 1/2 EXT', 'Quantity': 5, 'Category': 'Sockets'}, {'Item Name': '4PC 3/8" SOCKET EXTENSIONS', 'Item Number': 'HT 4P 3/8 EXT', 'Quantity': 3, 'Category': 'Sockets'}, {'Item Name': '2PC WOBBLY SET', 'Item Number': 'HT 2P Wbbly', 'Quantity': 4, 'Category': 'Sockets'}, {'Item Name': 'Metric wrench set', 'Item Number': 'HT Mtrc 14pc end wr', 'Quantity': 1, 'Category': 'Wrenches'}, {'Item Name': '8" Cresent wrench', 'Item Number': 'HT 8in crsnt wr', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': '10" Cresent wrench', 'Item Number': 'HT 10in crsnt wr', 'Quantity': 4, 'Category': 'Tool_Box'}, {'Item Name': '12" Cresent wrench', 'Item Number': 'HT 12in cresent wr', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': '15" cresent wrench', 'Item Number': 'HT 15in cresent wr', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'Tip Cleaner', 'Item Number': 'C wm650', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'Strikers', 'Item Number': 'C wm4501', 'Quantity': 5, 'Category': 'Tool_Box'}, {'Item Name': 'Cutting tip #1', 'Item Number': 'C 0330-0005', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'Cutting tip #2', 'Item Number': 'C 0330-0006', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'Cutting tip #3', 'Item Number': 'C 0330-0002', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'Inspection Mirror', 'Item Number': 'FT sm insp mrr', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'Chalk Box', 'Item Number': 'FT 47-140', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'Chalk bottle', 'Item Number': 'FT 93322', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'String Line', 'Item Number': 'Ft Strng ln', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'Plumb Bob', 'Item Number': 'FT 0905', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'Speed Square', 'Item Number': 'FT al tri sq', 'Quantity': 4, 'Category': 'Tool_Box'}, {'Item Name': "25' Tape measure", 'Item Number': 'FT 7526', 'Quantity': 4, 'Category': 'Tool_Box'}, {'Item Name': "50' Tape measure", 'Item Number': 'FT 0050', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'Torpedo Level', 'Item Number': 'FT 81-9', 'Quantity': 4, 'Category': 'Tool_Box'}, {'Item Name': '15/16 Reammer bit', 'Item Number': 'GC DRI 7/8R', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'Pointed Burr bit', 'Item Number': 'GC SG-5', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'ROUND BUR BIT FOR END GRINDER', 'Item Number': 'GC SC-5', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'PIPE WRENCH 14" STEEL', 'Item Number': 'HT 14IN PIPE WR', 'Quantity': 3, 'Category': 'Tool_Box'}, {'Item Name': 'PIPE WRENCH 18"', 'Item Number': 'HT 18IN PIPE WR', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'SCREWDRIVER SET', 'Item Number': 'HT 12P SCRW DR', 'Quantity': 3, 'Category': 'Tool_Box'}, {'Item Name': '12" CHANNELOCK PLIERS', 'Item Number': 'HT 12IN CHNL LCK', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'PLIER SET - NEEDLE NOSE, SIDECUT, LINEMAN,10"CHANNELOCK', 'Item Number': 'HT 5P PLR SET', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'VISE GRIP PLIERS', 'Item Number': 'HT 63872', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'PUNCH & CHISEL KIT', 'Item Number': 'HT 61044', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'FILE KIT', 'Item Number': 'HT 12IN FILE ST', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'LARGE WIZARD PIPE WRAP', 'Item Number': 'FT WW-17A', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'MEDIUM WIZARD PIPE WRAP', 'Item Number': 'FT WW-17', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'SMALL WIZARD PIPE WRAP', 'Item Number': 'FT WW-16', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'DRILL BIT SET', 'Item Number': 'PT KFD29J-PC', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'BULL PIN', 'Item Number': 'FT BLL PN', 'Quantity': 4, 'Category': 'Tool_Box'}, {'Item Name': 'C.S. WIRE HAND BRUSH', 'Item Number': 'W WM600416', 'Quantity': 4, 'Category': 'Tool_Box'}, {'Item Name': '7 PIECE ADAPTER SET', 'Item Number': 'HT 7PC IMPCT SCKT ADPTR', 'Quantity': 1, 'Category': 'Tool_Box'}, {'Item Name': 'CYLINDER CART', 'Item Number': 'C GRN TRCH CRT', 'Quantity': 1, 'Category': 'Torch/Cutting'}, {'Item Name': 'HOSE REPAIR KIT O2/ACETYLENE', 'Item Number': 'C WM26', 'Quantity': 2, 'Category': 'Torch/Cutting'}, {'Item Name': "OXYGEN / ACETYLENE HOSE 50'", 'Item Number': 'C 1-4x50 TRCH HOSE', 'Quantity': 5, 'Category': 'Torch/Cutting'}, {'Item Name': 'REGULATOR - ACETYLENE', 'Item Number': 'C ACET REG', 'Quantity': 2, 'Category': 'Torch/Cutting'}, {'Item Name': 'REGULATOR - OXYGEN', 'Item Number': 'C OXY REG', 'Quantity': 2, 'Category': 'Torch/Cutting'}, {'Item Name': 'ACETYLENE REGULATOR SAFETY CAP (IN USE TYPE)', 'Item Number': 'C 8032014', 'Quantity': 2, 'Category': 'Torch/Cutting'}, {'Item Name': 'OXYGEN REGULATOR SAFETY CAP (IN USE TYPE)', 'Item Number': 'C 8032010', 'Quantity': 2, 'Category': 'Torch/Cutting'}, {'Item Name': 'ROSEBUD', 'Item Number': 'C RS BUD', 'Quantity': 2, 'Category': 'Torch/Cutting'}, {'Item Name': 'TORCH HEADS HEAD&HANDLE VICTOR COMPLETE', 'Item Number': 'C CMPLT TRCH', 'Quantity': 2, 'Category': 'Torch/Cutting'}, {'Item Name': 'FLAMMABLE SIGN', 'Item Number': 'S FLAM SGN', 'Quantity': 2, 'Category': 'Torch/Cutting'}, {'Item Name': "1/0 welding lead 50'", 'Item Number': 'W WLDNG LD 50FT', 'Quantity': 10, 'Category': 'Welding'}, {'Item Name': 'STINGERS', 'Item Number': 'W WLDNG STNGR', 'Quantity': 4, 'Category': 'Welding'}, {'Item Name': 'GROUND CLAMPS', 'Item Number': 'W WLDNG GRND', 'Quantity': 4, 'Category': 'Welding'}, {'Item Name': '1/8" E7018 WELDING ROD 50. P', 'Item Number': 'W 1-8 7018', 'Quantity': '50', 'Category': 'Welding'}, {'Item Name': '3/32" E7018 WELDING ROD (50LB)', 'Item Number': 'W 3-32 7018', 'Quantity': '50', 'Category': 'Welding'}, {'Item Name': '6010 1/8 WELDING ROD 50', 'Item Number': 'W 1-8 6010', 'Quantity': '50', 'Category': 'Welding'}, {'Item Name': '308L 3/32" STAINLESS WELDING ROD', 'Item Number': 'W 3/32E308L-16', 'Quantity': '10', 'Category': 'Welding'}, {'Item Name': '3/32 E309L-16 STAINLESS WELDING', 'Item Number': 'W 1/8E309L-16', 'Quantity': '10', 'Category': 'Welding'}, {'Item Name': '1/8 316L STAINLESS WELD ROD', 'Item Number': 'W 1-8 316L', 'Quantity': '10', 'Category': 'Welding'}, {'Item Name': 'CORESHEILD ELEVEN - 045 WIRE', 'Item Number': 'W .045x33 CS11', 'Quantity': '2', 'Category': 'Welding'}, {'Item Name': '072 XLR8', 'Item Number': 'W .072x33 XLR8', 'Quantity': '2', 'Category': 'Welding'}, {'Item Name': 'ARGON FLOW METER', 'Item Number': 'W H355-AR-580', 'Quantity': 1, 'Category': 'Welding'}, {'Item Name': 'ARGON HOSE', 'Item Number': 'W CK ARH-50', 'Quantity': 2, 'Category': 'Welding'}, {'Item Name': '2X4 CLEAR WELDING HOOD LENS', 'Item Number': 'PPE SP-1', 'Quantity': 50, 'Category': 'Welding'}, {'Item Name': '2X4 WELDING LENS SHADE 9', 'Item Number': 'PPE 802410', 'Quantity': 20, 'Category': 'Welding'}, {'Item Name': 'SOAPSTONE', 'Item Number': 'FT FL5', 'Quantity': 1, 'Category': 'Welding'}, {'Item Name': 'PROFAX WHIP', 'Item Number': 'W 1260-15', 'Quantity': 3, 'Category': 'Welding'}, {'Item Name': 'TWECO WHIP', 'Item Number': 'W WMK4015116L', 'Quantity': 3, 'Category': 'Welding'}, {'Item Name': 'WELD HOOD, QUICK LOCK', 'Item Number': 'PPE 52006-SIL', 'Quantity': 2, 'Category': 'Welding'}, {'Item Name': 'WELDING SCREEN FRAME', 'Item Number': 'W 6X8VF1-SH8', 'Quantity': 1, 'Category': 'Welding'}, {'Item Name': 'FIRE BLANKET, 60" ROLL', 'Item Number': 'W 585-60', 'Quantity': 1, 'Category': 'Welding'}, {'Item Name': 'TWECO 045 TIPS', 'Item Number': 'W WS14H-45', 'Quantity': 50, 'Category': 'Welding_Consumables'}, {'Item Name': 'TWECO DIFFUSERS', 'Item Number': 'W WS54A', 'Quantity': 10, 'Category': 'Welding_Consumables'}, {'Item Name': 'TWECO NOZZLE', 'Item Number': 'W WS24A-62-SS', 'Quantity': 2, 'Category': 'Welding_Consumables'}, {'Item Name': 'LINCOLN CONSUMABLES KIT', 'Item Number': 'HK CNSMBLS BOX', 'Quantity': 1, 'Category': 'Welding_Consumables'}, {'Item Name': 'LINCOLN 072 TIPS', 'Item Number': 'W KP2100-1B1', 'Quantity': 50, 'Category': 'Welding_Consumables'}, {'Item Name': 'LINCOLN 045 TIPS', 'Item Number': 'W KP2105-2B1', 'Quantity': 50, 'Category': 'Welding_Consumables'}, {'Item Name': 'GOOSE NECK INSULATORS', 'Item Number': 'W KP2089-1', 'Quantity': 25, 'Category': 'Welding_Consumables'}, {'Item Name': '6" GOOSENECK', 'Item Number': 'W KP1914-2', 'Quantity': 2, 'Category': 'Welding_Consumables'}, {'Item Name': '12" GOOSENECK', 'Item Number': 'W KP1914-1', 'Quantity': 2, 'Category': 'Welding_Consumables'}, {'Item Name': 'DRIVE ROLL KIT (enough to swap out all the LNs)', 'Item Number': 'HK CNSMBLS BOX', 'Quantity': 1, 'Category': 'Welding_Consumables'}, {'Item Name': '072 ROLLER KIT', 'Item Number': 'W KP1697-068', 'Quantity': 2, 'Category': 'Welding_Consumables'}, {'Item Name': '045 ROLLER KIT', 'Item Number': 'W WS44-116-15', 'Quantity': 2, 'Category': 'Welding_Consumables'}, {'Item Name': 'TWECO CONSUMABLES BOX', 'Item Number': 'HK CNSMBLS BOX', 'Quantity': 1, 'Category': 'Welding_Consumables'}, {'Item Name': 'TWECO INSULATORS', 'Item Number': 'W WS34A', 'Quantity': 10, 'Category': 'Welding_Consumables'}, {'Item Name': 'Jumbo wrench set', 'Item Number': 'HT jmbo wr st', 'Quantity': 1, 'Category': 'Wrenches'}, {'Item Name': 'Tool bags for wrench sets', 'Item Number': 'HT 14Pckt tl rll', 'Quantity': 7, 'Category': 'Wrenches'}, {'Item Name': 'Standard Wrench sets', 'Item Number': 'HT 14pc end wr', 'Quantity': 6, 'Category': 'Wrenches'}, {'Item Name': 'Allen Wrench set Metric', 'Item Number': 'HT fldng mtrc hx st', 'Quantity': 2, 'Category': 'Tool_Box'}, {'Item Name': 'Allen Wrench set Standard', 'Item Number': 'HT fldng sae hx st', 'Quantity': 2, 'Category': 'Tool_Box'}]


semi_trailer_list = [
    {'Item Number': 'S Air Movr', 'Item Name': 'Venilation Fan', 'Quantity': 2, 'Category': 'AIR'},
    {'Item Number': 'S WHP CHK', 'Item Name': 'Whip Checks', 'Quantity': 10, 'Category': 'AIR'},
    {'Item Number': 'PT 713-20665550', 'Item Name': 'Chicago Air Hose', 'Quantity': 10, 'Category': 'AIR'},
    {'Item Number': 'Fillers', 'Item Name': 'Husky Air Fittings', 'Quantity': 5, 'Category': 'AIR'},
    {'Item Number': 'PT Chgo Clip', 'Item Name': 'Saftey Pins for Air Hose', 'Quantity': 5, 'Category': 'AIR'},
    {'Item Number': 'PT Air zip gun', 'Item Name': 'Air Zip Gun', 'Quantity': 2, 'Category': 'AIR'},
    {'Item Number': 'PT 3-way chic', 'Item Name': 'Chicago Y Fitting', 'Quantity': 1, 'Category': 'AIR'},
    {'Item Number': 'PT Bll vlve 1-2', 'Item Name': 'Chicago Ball Valve', 'Quantity': 1, 'Category': 'AIR'},
    {'Item Number': 'pt chgo grmt', 'Item Name': 'Chicago Grommets', 'Quantity': 5, 'Category': 'AIR'},
    {'Item Number': 'PT Rivit Bstr', 'Item Name': 'Rivet Buster', 'Quantity': 1, 'Category': 'AIR'},
    {'Item Number': 'pt 1 impact', 'Item Name': '1" Air Impact', 'Quantity': 1, 'Category': 'AIR'},
    {'Item Number': 'PT L02h12', 'Item Name': 'Chisel Bit for Rivet Buster', 'Quantity': 1, 'Category': 'AIR'},
    {'Item Number': 'PT l03h12', 'Item Name': 'Pointed bit for Rivet Buster', 'Quantity': 1, 'Category': 'AIR'},
    {'Item Number': 'PT 4005', 'Item Name': 'Needle Gun', 'Quantity': 2, 'Category': 'AIR'},
    {'Item Number': 'w 22-043-003', 'Item Name': '1/4 AIRARC ROD 50 PER BOX', 'Quantity': 2, 'Category': 'AIR'},
    {'Item Number': 'W 22-063-003', 'Item Name': '3/8 AIRARC ROD 50 PER BOX', 'Quantity': 4, 'Category': 'AIR'},
    {'Item Number': 'C 61-082-006', 'Item Name': 'AIR ARC GOUGING GUN', 'Quantity': 2, 'Category': 'AIR'},
    {'Item Number': 'EL 1002 109 690', 'Item Name': '100 WATT LIGHT BULBS', 'Quantity': 4, 'Category': 'Electrical'},
    {'Item Number': 'EL 04-00105', 'Item Name': '110V 12/3 3-WAY GROUND FAULT INERRUPTER', 'Quantity': 10, 'Category': 'Electrical'},
    {'Item Number': 'EL 74050PK2V2', 'Item Name': "110V 12/3 EXTENSION CORD 50'", 'Quantity': 30, 'Category': 'Electrical'},
    {'Item Number': 'EL 542 246', 'Item Name': '110V DROP LIGHT 100W RS BULB', 'Quantity': 5, 'Category': 'Electrical'},
    {'Item Number': 'EL 1001 863 376', 'Item Name': 'PORTABLE HALOGEN WORKLIGHT', 'Quantity': 4, 'Category': 'Electrical'},
    {'Item Number': 'FT 410P', 'Item Name': '10" C-CLAMPS', 'Quantity': 6, 'Category': 'Fitting'},
    {'Item Number': 'FT UM125', 'Item Name': '12 "ADJUSTABLE L-CLAMPS', 'Quantity': 6, 'Category': 'Fitting'},
    {'Item Number': 'F CBY CLMP', 'Item Name': 'COWBOY CLAMPS', 'Quantity': 6, 'Category': 'Fitting'},
    {'Item Number': 'FT 71.78', 'Item Name': "LARGE LEVEL (OVER 6')", 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 75.48', 'Item Name': 'LEVEL 4FT', 'Quantity': 2, 'Category': 'Fitting'},
    {'Item Number': 'FT 75.24', 'Item Name': 'LEVEL 2FT', 'Quantity': 2, 'Category': 'Fitting'},
    {'Item Number': 'HT B65115', 'Item Name': 'PORTA POWER PUMPS AND CLYINDER', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 4100 PIPE STND', 'Item Name': '"V" HEAD PIPE STAND', 'Quantity': 6, 'Category': 'Fitting'},
    {'Item Number': 'FL 2 CYCL OIL', 'Item Name': '2-CYCLE OIL, QUART', 'Quantity': 2, 'Category': 'Flam_Cabinet'},
    {'Item Number': 'FL 75-600', 'Item Name': 'TUBE OF GREASE', 'Quantity': 2, 'Category': 'Flam_Cabinet'},
    {'Item Number': 'FL 383732', 'Item Name': 'AIR TOOL OIL', 'Quantity': 1, 'Category': 'Flam_Cabinet'},
    {'Item Number': 'FL 30203', 'Item Name': 'CUTTING OIL (1 GALLON)', 'Quantity': 1, 'Category': 'Flam_Cabinet'},
    {'Item Number': 'HT 715-1230', 'Item Name': 'GREASE GUN', 'Quantity': 1, 'Category': 'Flam_Cabinet'},
    {'Item Number': 'FL HYD FL', 'Item Name': 'HYDRAULIC FLUID, 1 QUART', 'Quantity': 1, 'Category': 'Flam_Cabinet'},
    {'Item Number': 'FL OIL 10w-40', 'Item Name': 'MOTOR OIL, 10W-40, QUART', 'Quantity': 2, 'Category': 'Flam_Cabinet'},
    {'Item Number': 'FL 1673', 'Item Name': 'PENETRATING OIL, SPRAY', 'Quantity': 4, 'Category': 'Flam_Cabinet'},
    {'Item Number': 'GC 76318', 'Item Name': 'FLAPPER WHEEL', 'Quantity': 40, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC R4K58', 'Item Name': '4" STRINGER BEAD WIRE WHEEL CS', 'Quantity': 20, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC 22047', 'Item Name': '6" Cutting disc', 'Quantity': 400, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC 20160', 'Item Name': '4.5" GRINDING DISC', 'Quantity': 80, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC AWD40', 'Item Name': '4" MASON GRINDING DIAMOND CUP', 'Quantity': 2, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'HT 36IN PIPE WR', 'Item Name': 'PIPE WRENCH 36"', 'Quantity': 1, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT BLT CTTRS', 'Item Name': 'BOLT CUTTERS, 24" X 3/8"', 'Quantity': 1, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT 1554300', 'Item Name': 'RD SHOVEL, LONG OR SHORT', 'Quantity': 2, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT 618004', 'Item Name': 'SQ SHOVEL, LONG OR SHORT', 'Quantity': 2, 'Category': 'Hammer_Rack'},
    {'Item Number': 'FT 7168', 'Item Name': 'SLEAVER BAR', 'Quantity': 8, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT 1000 014 755', 'Item Name': 'MILL BAR', 'Quantity': 2, 'Category': 'Hammer_Rack'},
    {'Item Number': 'FT 1110', 'Item Name': 'FRAMING SQUARE', 'Quantity': 2, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT WH-30', 'Item Name': 'CHIPPING HAMMER', 'Quantity': 7, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT 1000 300 224', 'Item Name': 'CLAW HAMMER', 'Quantity': 2, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT DEAD BLW 4LB', 'Item Name': 'DEAD BLOW HAMMER 4LB', 'Quantity': 1, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT 4LB', 'Item Name': 'HEAVY HAMMER 4LB', 'Quantity': 8, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT 10LB', 'Item Name': 'HEAVY HAMMER 10#', 'Quantity': 2, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HK 00528', 'Item Name': 'BROOM, PUSH', 'Quantity': 1, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT HD BCKT', 'Item Name': '5 Gallon Buckets', 'Quantity': 10, 'Category': 'House_keeping'},
    {'Item Number': 'Saftey', 'Item Name': 'BLANK TAGS', 'Quantity': 30, 'Category': 'House_keeping'},
    {'Item Number': 'Melt', 'Item Name': 'ICE MELT (ONLY IF IN SEASON)', 'Quantity': 1, 'Category': 'House_keeping'},
    {'Item Number': 'HK 1926946', 'Item Name': 'TRASH CAN w/ LIDS', 'Quantity': 2, 'Category': 'House_keeping'},
    {'Item Number': 'HK 960 362', 'Item Name': 'TRASH BAGS 55 GAL.', 'Quantity': 2, 'Category': 'House_keeping'},
    {'Item Number': 'HT HD800P', 'Item Name': '2 WHEEL HAND TRUCK', 'Quantity': 1, 'Category': 'House_keeping'},
    {'Item Number': 'HT HD109D', 'Item Name': 'CAULKING GUN', 'Quantity': 2, 'Category': 'House_keeping'},
    {'Item Number': 'HT 20TON BTL JCK', 'Item Name': 'BOTTLE JACK', 'Quantity': 2, 'Category': 'House_keeping'},
    {'Item Number': 'Flare', 'Item Name': 'FLARE CARDS', 'Quantity': 100, 'Category': 'House_keeping'},
    {'Item Number': 'HT 05337', 'Item Name': 'TIE WIRE (16 GAUGE)', 'Quantity': 2, 'Category': 'House_keeping'},
    {'Item Number': 'S GOJO LRG', 'Item Name': 'HAND CLEANER WIPES BUCKET', 'Quantity': 2, 'Category': 'House_keeping'},
    {'Item Number': 'S EXT LDDR 24FT', 'Item Name': 'EXTENSION LADDER', 'Quantity': 1, 'Category': 'Ladder'},
    {'Item Number': 'S AFRAME 8FT', 'Item Name': "STEP LADDER 8'", 'Quantity': 1, 'Category': 'Ladder'},
    {'Item Number': 'PT DW511', 'Item Name': '1/2" DRILL MOTOR', 'Quantity': 2, 'Category': 'Power_Tools'},
    {'Item Number': 'PT 1-2IMPACT', 'Item Name': '1/2" IMPACT WRENCH', 'Quantity': 4, 'Category': 'Power_Tools'},
    {'Item Number': 'PT DW294', 'Item Name': '3/4" IMPACT WRENCH', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT HMMRDRLL SDSMAX', 'Item Name': 'SDS HAMMER DRILL', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT MAG DRLL', 'Item Name': '1/2" MAGNETIC DRILL PRESS', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT DIE GRNDR', 'Item Name': 'DIE GRINDER', 'Quantity': 2, 'Category': 'Power_Tools'},
    {'Item Number': 'PT DWE402', 'Item Name': '4-1/2" ANGLE GRINDER', 'Quantity': 8, 'Category': 'Power_Tools'},
    {'Item Number': 'PT WEP 15-150', 'Item Name': '6" ANGLE GRINDER (Metabo)', 'Quantity': 8, 'Category': 'Power_Tools'},
    {'Item Number': 'PT GA9031Y', 'Item Name': '9" ANGLE GRINDER', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT 3204', 'Item Name': '7-1/4" CIRCULAR SAW 110V', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT BND SW', 'Item Name': 'PORTABLE BAND SAW 110V 6 AMPS', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'C 48 39 0524', 'Item Name': 'PORTABLE BAND SAW BLADES', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT SWZALL', 'Item Name': 'SAWSALL 110V 13AMPS', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT 48 00 5093', 'Item Name': 'SAWSALL BLADE 6" Package', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'RG 38-G CABLE', 'Item Name': '100ft 3/8" cable', 'Quantity': 1, 'Category': 'Rigging'},
    {'Item Number': 'Crosby', 'Item Name': '3/8" CROSBY CLAMPS', 'Quantity': 15, 'Category': 'Rigging'},
    {'Item Number': 'RG LH34T', 'Item Name': '3/4 TON, CHAIN COME-A-LONGS', 'Quantity': 8, 'Category': 'Rigging'},
    {'Item Number': 'RG LH15T', 'Item Name': '1 1/2 TON, CHAIN COME-A-LONGS', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG LH3T', 'Item Name': '3 TON, CHAIN COME-A-LONGS', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG CF1T', 'Item Name': '1 TON, LIFT CHAIN X PULL CHAIN', 'Quantity': 8, 'Category': 'Rigging'},
    {'Item Number': 'RG CF2T', 'Item Name': '2 TON, LIFT CHAIN X PULL CHAIN', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG CF3T', 'Item Name': '3 TON, LIFT CHAIN X PULL CHAIN', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG CC 38-4', 'Item Name': '3/8" X 4\' CHOKER', 'Quantity': 6, 'Category': 'Rigging'},
    {'Item Number': 'RG CC 12-20', 'Item Name': '1/2" X 20\' CHOKER', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG CC 12-10', 'Item Name': '1/2" X 10\' CHOKER', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG CC 34-20', 'Item Name': '3/4" X 20\' CHOKER', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG CC 34-10', 'Item Name': '3/4" X 10\' CHOKER', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG 2TBMCLMP', 'Item Name': 'BEAM CLAMP, 2 TON', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 1-2', 'Item Name': 'SHACKLES 1/2"', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 5-8', 'Item Name': 'SHACKLES 5/8"', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 3-4', 'Item Name': 'SHACKLES 3/4"', 'Quantity': 6, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 7-8', 'Item Name': 'SHACKLES 7/8"', 'Quantity': 8, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 1', 'Item Name': 'SHACKLES 1"', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 1-1/4', 'Item Name': 'SHACKLES 1-1/4"', 'Quantity': 4, 'Category': 'Rigging'},
    {'Item Number': 'RG SNTCH BLK 418', 'Item Name': 'SNATCH (LIFT) BLOCK, 2-5 TON', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'HT 195522', 'Item Name': 'ROPE FOR TAGLINE', 'Quantity': 1, 'Category': 'Rigging'},
    {'Item Number': 'RG YLLW 10FT', 'Item Name': 'YELLOW 10FT', 'Quantity': 6, 'Category': 'Rigging'},
    {'Item Number': 'RG YLLW 20FT', 'Item Name': 'YELLOW 20FT', 'Quantity': 6, 'Category': 'Rigging'},
    {'Item Number': 'RG RED 10FT', 'Item Name': 'RED 10FT', 'Quantity': 6, 'Category': 'Rigging'},
    {'Item Number': 'RG RED 20FT', 'Item Name': 'RED 20FT', 'Quantity': 6, 'Category': 'Rigging'},
    {'Item Number': 'RG GRN 6FT', 'Item Name': 'GREEN 6FT', 'Quantity': 6, 'Category': 'Rigging'},
    {'Item Number': 'RG STRP 2-4', 'Item Name': '2" X 4FT FLAT STRAP', 'Quantity': 6, 'Category': 'Rigging'},
    {'Item Number': 'RG STRP 1-4', 'Item Name': '1" X 4FT FLAT STRAP', 'Quantity': 6, 'Category': 'Rigging'},
    {'Item Number': 'S 9501403', 'Item Name': 'SUSPENSION TRAUMA SAFETY STRAP', 'Quantity': '6', 'Category': 'Rigging'},
    {'Item Number': 'S UC1700', 'Item Name': 'WHEEL CHOCKS', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'S VEH PREOP', 'Item Name': 'VEHICHLE PRE OP BOOK', 'Quantity': 8, 'Category': 'Saftey'},
    {'Item Number': 'S EQ PREOP', 'Item Name': 'EQUIPMENT PRE OP BOOK', 'Quantity': 8, 'Category': 'Saftey'},
    {'Item Number': 'S SHOE GRD', 'Item Name': 'FOOT GAURDS', 'Quantity': 8, 'Category': 'Saftey'},
    {'Item Number': 'S ICE CLT', 'Item Name': 'Ice Cleats', 'Quantity': 8, 'Category': 'Saftey'},
    {'Item Number': 'PPE WM801000', 'Item Name': 'CLEAR FACESHIELD', 'Quantity': 40, 'Category': 'Saftey'},
    {'Item Number': 'PPE WM858150', 'Item Name': 'DARK FACESHIELD', 'Quantity': 15, 'Category': 'Saftey'},
    {'Item Number': 'PPE 4110S', 'Item Name': 'SAFETY GLASSES CLEAR', 'Quantity': 24, 'Category': 'Saftey'},
    {'Item Number': 'PPE 932-1', 'Item Name': 'GOGGLES, CLEAR LENS', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'PPE 3200BS S', 'Item Name': 'GLOVES SMALL', 'Quantity': 72, 'Category': 'Saftey'},
    {'Item Number': 'PPE 3200BS M', 'Item Name': 'GLOVES MEDIUM', 'Quantity': 72, 'Category': 'Saftey'},
    {'Item Number': 'PPE 3200BS L', 'Item Name': 'GLOVES LARGE', 'Quantity': 72, 'Category': 'Saftey'},
    {'Item Number': 'PPE 3200BS XL', 'Item Name': 'GLOVES X-LARGE', 'Quantity': 48, 'Category': 'Saftey'},
    {'Item Number': 'PPE 320L', 'Item Name': 'WELDING GLOVES', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'PPE 7MIL GLV', 'Item Name': 'L-LATEX GLOVES', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'PPE 6800', 'Item Name': 'EAR PLUG REFILL', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'PPE E-2RW BLACK', 'Item Name': 'HARD HAT', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'W SPEEDY-LOOP M5000', 'Item Name': 'Halo', 'Quantity': 10, 'Category': 'Saftey'},
    {'Item Number': 'PPE 8210', 'Item Name': 'DISPOSABLE DUST RESP. WELDING', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'PPE SA00818', 'Item Name': 'RESPIRATOR CARTRIDGES MILLER', 'Quantity': 20, 'Category': 'Saftey'},
    {'Item Number': 'PPE ML00895', 'Item Name': 'RESPIRATORY 1/2 MASK L MILLER', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'PPE 1001', 'Item Name': 'RESPIRATORY WIPES', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'HK ZIPLC 1GAL', 'Item Name': 'ZIPLOC BAGS 1 GALLON', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'PPE 6691UL', 'Item Name': 'SAFETY VEST - LARGE', 'Quantity': 8, 'Category': 'Saftey'},
    {'Item Number': 'PPE 6691UXL', 'Item Name': 'SAFETY VEST XL', 'Quantity': 8, 'Category': 'Saftey'},
    {'Item Number': 'PPE TY127S-3XL', 'Item Name': 'TYVEK COVERALL 3XL W/HOOD & BO', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'PPE SRL LNYRD', 'Item Name': 'SRL LANYARD', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'PPE 96426RR', 'Item Name': '6ft tie off cheater', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'PPE 01705A', 'Item Name': 'FULL BODY HARNESS MD/LG', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'S 30FT YOYO', 'Item Name': "YO YO 30'", 'Quantity': 4, 'Category': 'Saftey'},
    {'Item Number': 'S TRFFC CN 18IN', 'Item Name': 'ORANGE TRAFFIC CONES', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'S 77-1001', 'Item Name': '"CAUTION" BARRICADE TAPE (YELLOW)', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'S 77-1004', 'Item Name': '"DANGER" BARRICADE TAPE (RED)', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'S A1107BLUKD', 'Item Name': 'PADLOCKS WITH KEYS (LOCK OUT LOCKS)', 'Quantity': 48, 'Category': 'Saftey'},
    {'Item Number': 'BOX', 'Item Name': 'LOCKOUT BOX', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'S ML420', 'Item Name': 'LOCK-OUT HASPS', 'Quantity': 8, 'Category': 'Saftey'},
    {'Item Number': 'S 782796', 'Item Name': 'CASES OF WATER', 'Quantity': 10, 'Category': 'Saftey'},
    {'Item Number': 'HT 1528195', 'Item Name': 'DUCT TAPE', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'S 452', 'Item Name': 'EYE WASH BOTTLES', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'FIRE', 'Item Name': 'FIRE EXTINGUISHER TAG', 'Quantity': 3, 'Category': 'Saftey'},
    {'Item Number': 'FIRE2', 'Item Name': 'FIRE EXTINGUISHER BREAK AWAY TIE', 'Quantity': 3, 'Category': 'Saftey'},
    {'Item Number': 'FIRE3', 'Item Name': 'FIRE EXTINGUISHER PIN', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'FIRE4', 'Item Name': 'FIRE EXTINGUISHER, 20# ABC (Must be insp. And tagged)', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'S 91339', 'Item Name': 'FIRST AID KIT, LARGE (Check Expiration)', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'TAPE', 'Item Name': 'SEASONAL INSPECTION TAPE', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'S OIL SPLL KIT', 'Item Name': 'OIL SPILL CONTAINMENT KIT', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'S 22CN05', 'Item Name': 'LOCK OUT TAGS', 'Quantity': 48, 'Category': 'Saftey'},
    {'Item Number': 'S TAR128', 'Item Name': 'BARRICADE TAGS', 'Quantity': 48, 'Category': 'Saftey'},
    {'Item Number': 'HT 13P 1/2 SKT', 'Item Name': '1/2" DRIVE SOCKET SET', 'Quantity': 4, 'Category': 'Sockets'},
    {'Item Number': 'HT 3-4 SCKT ST', 'Item Name': '3/4" DRIVE SOCKET SET', 'Quantity': 1, 'Category': 'Sockets'},
    {'Item Number': 'HT 21P 3/8 SKT', 'Item Name': '3/8" DRIVE SOCKET SET STD AND METRIC', 'Quantity': 2, 'Category': 'Sockets'},
    {'Item Number': 'HT HX SCKT ST SAE', 'Item Name': 'HEX HEAD SOCKET SET STANDARD', 'Quantity': 1, 'Category': 'Sockets'},
    {'Item Number': 'HT HX SCKT ST METRIC', 'Item Name': 'HEX HEAD SOCKET SET METRIC', 'Quantity': 1, 'Category': 'Sockets'},
    {'Item Number': 'HT MT AMO BX', 'Item Name': 'METAL AMMO CAN FOR 1/2" SOCKET SETS', 'Quantity': 5, 'Category': 'Sockets'},
    {'Item Number': 'HT PL AMO BX', 'Item Name': 'PLASTIC AMMO CAN FOR 3/8 AND HEX SETS', 'Quantity': 3, 'Category': 'Sockets'},
    {'Item Number': 'HT MTRC 1-2 SCKT ST', 'Item Name': 'METRIC 1/2 INCH SOCKET SET', 'Quantity': 1, 'Category': 'Sockets'},
    {'Item Number': 'HT 3/8 RTCHT', 'Item Name': '3/8" RATCHET FOR SOCKET AND HEX SETS', 'Quantity': 3, 'Category': 'Sockets'},
    {'Item Number': 'HT 1/2 Rtcht', 'Item Name': '1/2" RATCHETS FOR SOCKET SETS', 'Quantity': 5, 'Category': 'Sockets'},
    {'Item Number': 'HT 4P 1/2 EXT', 'Item Name': '4PC 1/2" SOCKET EXTENSIONS', 'Quantity': 5, 'Category': 'Sockets'},
    {'Item Number': 'HT 4P 3/8 EXT', 'Item Name': '4PC 3/8" SOCKET EXTENSIONS', 'Quantity': 3, 'Category': 'Sockets'},
    {'Item Number': 'HT 2P Wbbly', 'Item Name': '2PC WOBBLY SET', 'Quantity': 4, 'Category': 'Sockets'},
    {'Item Number': 'HT 8in crsnt wr', 'Item Name': '8" Cresent wrench', 'Quantity': 2, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 10in crsnt wr', 'Item Name': '10" Cresent wrench', 'Quantity': 4, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 12in cresent wr', 'Item Name': '12" Cresent wrench', 'Quantity': 2, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 15in cresent wr', 'Item Name': '15" cresent wrench', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'C wm650', 'Item Name': 'Tip Cleaner', 'Quantity': 2, 'Category': 'Tool_Box'},
    {'Item Number': 'C wm4501', 'Item Name': 'Strikers', 'Quantity': 5, 'Category': 'Tool_Box'},
    {'Item Number': 'C 0330-0005', 'Item Name': 'Cutting tip #1', 'Quantity': 4, 'Category': 'Tool_Box'},
    {'Item Number': 'C 0330-0006', 'Item Name': 'Cutting tip #2', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'C 0330-0002', 'Item Name': 'Cutting tip #3', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'FT sm insp mrr', 'Item Name': 'Inspection Mirror', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'FT 47-140', 'Item Name': 'Chalk Box', 'Quantity': 2, 'Category': 'Tool_Box'},
    {'Item Number': 'FT 93322', 'Item Name': 'Chalk bottle', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'Ft Strng ln', 'Item Name': 'String Line', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'FT 0905', 'Item Name': 'Plumb Bob', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'FT al tri sq', 'Item Name': 'Speed Square', 'Quantity': 6, 'Category': 'Tool_Box'},
    {'Item Number': 'FT 7526', 'Item Name': "25' Tape measure", 'Quantity': 6, 'Category': 'Tool_Box'},
    {'Item Number': 'FT 0050', 'Item Name': "50' Tape measure", 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'FT 81-9', 'Item Name': 'Torpedo Level', 'Quantity': 6, 'Category': 'Tool_Box'},
    {'Item Number': 'GC DRI 7/8R', 'Item Name': '15/16 Reammer bit', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'GC SG-5', 'Item Name': 'Pointed Burr bit', 'Quantity': 6, 'Category': 'Tool_Box'},
    {'Item Number': 'GC SC-5', 'Item Name': 'ROUND BUR BIT FOR END GRINDER', 'Quantity': 6, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 14IN PIPE WR', 'Item Name': 'PIPE WRENCH 14" STEEL', 'Quantity': 3, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 18IN PIPE WR', 'Item Name': 'PIPE WRENCH 18"', 'Quantity': 2, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 12P SCRW DR', 'Item Name': 'SCREWDRIVER SET', 'Quantity': 4, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 12IN CHNL LCK', 'Item Name': '12" CHANNELOCK PLIERS', 'Quantity': 2, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 5P PLR SET', 'Item Name': 'PLIER SET - NEEDLE NOSE, SIDECUT, LINEMAN,10"CHANNELOCK', 'Quantity': 4, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 63872', 'Item Name': 'VISE GRIP PLIERS', 'Quantity': 2, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 61044', 'Item Name': 'PUNCH & CHISEL KIT', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 12IN FILE ST', 'Item Name': 'FILE KIT', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'FT WW-17A', 'Item Name': 'LARGE WIZARD PIPE WRAP', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'FT WW-17', 'Item Name': 'MEDIUM WIZARD PIPE WRAP', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'FT WW-16', 'Item Name': 'SMALL WIZARD PIPE WRAP', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'PT KFD29J-PC', 'Item Name': 'DRILL BIT SET', 'Quantity': 4, 'Category': 'Tool_Box'},
    {'Item Number': 'FT BLL PN', 'Item Name': 'BULL PIN', 'Quantity': 6, 'Category': 'Tool_Box'},
    {'Item Number': 'W WM600416', 'Item Name': 'C.S. WIRE HAND BRUSH', 'Quantity': 6, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 7PC IMPCT SCKT ADPTR', 'Item Name': '7 PIECE ADAPTER SET', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'HT fldng mtrc hx st', 'Item Name': 'Allen Wrench set Metric', 'Quantity': 2, 'Category': 'Tool_Box'},
    {'Item Number': 'HT fldng sae hx st', 'Item Name': 'Allen Wrench set Standard', 'Quantity': 2, 'Category': 'Tool_Box'},
    {'Item Number': 'C GRN TRCH CRT', 'Item Name': 'CYLINDER CART', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C WM26', 'Item Name': 'HOSE REPAIR KIT O2/ACETYLENE', 'Quantity': 2, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 1-4x50 TRCH HOSE', 'Item Name': "OXYGEN / ACETYLENE HOSE 50'", 'Quantity': 5, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C ACET REG', 'Item Name': 'REGULATOR - ACETYLENE', 'Quantity': 2, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C OXY REG', 'Item Name': 'REGULATOR - OXYGEN', 'Quantity': 2, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 8032014', 'Item Name': 'ACETYLENE REGULATOR SAFETY CAP (IN USE TYPE)', 'Quantity': 2, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 8032010', 'Item Name': 'OXYGEN REGULATOR SAFETY CAP (IN USE TYPE)', 'Quantity': 2, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C RS BUD', 'Item Name': 'ROSEBUD', 'Quantity': 2, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C CMPLT TRCH', 'Item Name': 'TORCH HEADS HEAD&HANDLE VICTOR COMPLETE', 'Quantity': 2, 'Category': 'Torch/Cutting'},
    {'Item Number': 'S FLAM SGN', 'Item Name': 'FLAMMABLE SIGN', 'Quantity': 2, 'Category': 'Torch/Cutting'},
    {'Item Number': 'W WLDNG LD 50FT', 'Item Name': "1/0 welding lead 50'", 'Quantity': 20, 'Category': 'Welding'},
    {'Item Number': 'W WLDNG STNGR', 'Item Name': 'STINGERS', 'Quantity': 8, 'Category': 'Welding'},
    {'Item Number': 'W WLDNG GRND', 'Item Name': 'GROUND CLAMPS', 'Quantity': 8, 'Category': 'Welding'},
    {'Item Number': 'W 1-8 7018', 'Item Name': '1/8" E7018 WELDING ROD 50LB. P', 'Quantity': '100', 'Category': 'Welding'},
    {'Item Number': 'W 3-32 7018', 'Item Name': '3/32" E7018 WELDING ROD (50LB)', 'Quantity': '100', 'Category': 'Welding'},
    {'Item Number': 'W 1-8 6010', 'Item Name': '6010 1/8 WELDING ROD 50lb', 'Quantity': '100', 'Category': 'Welding'},
    {'Item Number': 'W 3/32E308L-16', 'Item Name': '308L 3/32" STAINLESS WELDING ROD', 'Quantity': '10', 'Category': 'Welding'},
    {'Item Number': 'W 1/8E309L-16', 'Item Name': '3/32 E309L-16 STAINLESS WELDING', 'Quantity': '10', 'Category': 'Welding'},
    {'Item Number': 'W 1-8 316L', 'Item Name': '1/8 316L STAINLESS WELD ROD', 'Quantity': '10', 'Category': 'Welding'},
    {'Item Number': 'W .045x33 CS11', 'Item Name': 'CORESHEILD ELEVEN - 045 WIRE', 'Quantity': '4', 'Category': 'Welding'},
    {'Item Number': 'W .072x33 XLR8', 'Item Name': '072 XLR8', 'Quantity': '4', 'Category': 'Welding'},
    {'Item Number': 'W H355-AR-580', 'Item Name': 'ARGON FLOW METER', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'W CK ARH-50', 'Item Name': 'ARGON HOSE', 'Quantity': 2, 'Category': 'Welding'},
    {'Item Number': 'PPE SP-1', 'Item Name': '2X4 CLEAR WELDING HOOD LENS', 'Quantity': 100, 'Category': 'Welding'},
    {'Item Number': 'PPE 802410', 'Item Name': '2X4 WELDING LENS SHADE 9', 'Quantity': 50, 'Category': 'Welding'},
    {'Item Number': 'FT FL5', 'Item Name': 'SOAPSTONE', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'W 1260-15', 'Item Name': 'PROFAX WHIP', 'Quantity': 3, 'Category': 'Welding'},
    {'Item Number': 'W WMK4015116L', 'Item Name': 'TWECO WHIP', 'Quantity': 3, 'Category': 'Welding'},
    {'Item Number': 'PPE 52006-SIL', 'Item Name': 'WELD HOOD, QUICK LOCK', 'Quantity': 2, 'Category': 'Welding'},
    {'Item Number': 'W 6X8VF1-SH8', 'Item Name': 'WELDING SCREEN FRAME', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'W 585-60', 'Item Name': 'FIRE BLANKET, 60" ROLL', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'W WS14H-45', 'Item Name': 'TWECO 045 TIPS', 'Quantity': 50, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W WS54A', 'Item Name': 'TWECO DIFFUSERS', 'Quantity': 10, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W WS24A-62-SS', 'Item Name': 'TWECO NOZZLE', 'Quantity': 2, 'Category': 'Welding_Consumables'},
    {'Item Number': 'HK CNSMBLS BOX', 'Item Name': 'LINCOLN CONSUMABLES KIT', 'Quantity': 1, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W KP2100-1B1', 'Item Name': 'LINCOLN 072 TIPS', 'Quantity': 50, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W KP2105-2B1', 'Item Name': 'LINCOLN 045 TIPS', 'Quantity': 50, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W KP2089-1', 'Item Name': 'GOOSE NECK INSULATORS', 'Quantity': 25, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W KP1914-2', 'Item Name': '6" GOOSENECK', 'Quantity': 2, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W KP1914-1', 'Item Name': '12" GOOSENECK', 'Quantity': 2, 'Category': 'Welding_Consumables'},
    {'Item Number': 'HK CNSMBLS BOX', 'Item Name': 'DRIVE ROLL KIT (enough to swap out all the LNs)', 'Quantity': 1, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W KP1697-068', 'Item Name': '072 ROLLER KIT', 'Quantity': 2, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W WS44-116-15', 'Item Name': '045 ROLLER KIT', 'Quantity': 2, 'Category': 'Welding_Consumables'},
    {'Item Number': 'HK CNSMBLS BOX', 'Item Name': 'TWECO CONSUMABLES BOX', 'Quantity': 1, 'Category': 'Welding_Consumables'},
    {'Item Number': 'W WS34A', 'Item Name': 'TWECO INSULATORS', 'Quantity': 10, 'Category': 'Welding_Consumables'},
    {'Item Number': 'HT Mtrc 14pc end wr', 'Item Name': 'Metric wrench set', 'Quantity': 1, 'Category': 'Wrenches'},
    {'Item Number': 'HT jmbo wr st', 'Item Name': 'Jumbo wrench set', 'Quantity': 1, 'Category': 'Wrenches'},
    {'Item Number': 'HT 14Pckt tl rll', 'Item Name': 'Tool bags for wrench sets', 'Quantity': 7, 'Category': 'Wrenches'},
    {'Item Number': 'HT 14pc end wr', 'Item Name': 'Standard Wrench sets', 'Quantity': 6, 'Category': 'Wrenches'},
]


gang_box_list =  [ {'Item Number': 'EL 04-00105', 'Item Name': '3-way GFCI', 'Quantity': 1, 'Category': 'Electrical'},
    {'Item Number': 'EL 542 246', 'Item Name': 'Drop Lights', 'Quantity': 1, 'Category': 'Electrical'},
    {'Item Number': 'EL 74050PK2V2', 'Item Name': 'Extension cord 50\'', 'Quantity': 4, 'Category': 'Electrical'},
    {'Item Number': 'FT 410P', 'Item Name': '10" C-Clamps', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'HT 1001 713 492', 'Item Name': '10lb Hammer', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT UM125', 'Item Name': '12" L-Clamp', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'HT 4LB', 'Item Name': '4lb Hammer', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'HT WH-30', 'Item Name': 'Chipping Hammer', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'HT 1000 300 224', 'Item Name': 'Claw Hammer', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'F CBY CLMP', 'Item Name': 'Cowboy Clamp', 'Quantity': 2, 'Category': 'Fitting'},
    {'Item Number': 'HT 14IN PIPE WR', 'Item Name': 'Pipe Wrench 14"', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 7168', 'Item Name': 'Sleaver Bar', 'Quantity': 2, 'Category': 'Fitting'},
    {'Item Number': 'FT AL TRI SQ', 'Item Name': 'Speed Square', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 7526', 'Item Name': 'Tape measure 25\'', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 81-9', 'Item Name': 'Torpedo level', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'GC R4K58', 'Item Name': '4" wire wheel', 'Quantity': 5, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC 20160', 'Item Name': '4.5" Grinding disc', 'Quantity': 10, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC 22047', 'Item Name': '6" cutting disc', 'Quantity': 50, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC 76318', 'Item Name': 'Flapper Wheels', 'Quantity': 10, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'PT DW511', 'Item Name': '1/2" Drill', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT 1-2IMPACT', 'Item Name': '1/2" Impact', 'Quantity': 2, 'Category': 'Power_Tools'},
    {'Item Number': 'PT DWE402', 'Item Name': '4.5" grinder', 'Quantity': 2, 'Category': 'Power_Tools'},
    {'Item Number': 'PT WEP 15-150', 'Item Name': '6" grinder', 'Quantity': 2, 'Category': 'Power_Tools'},
    {'Item Number': 'RG CF1T', 'Item Name': '1T Chain Fall', 'Quantity': 1, 'Category': 'Rigging'},
    {'Item Number': 'RG STRP 1-4', 'Item Name': '1x4 flat strap', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG STRP 2-4', 'Item Name': '2x4 flat strap', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG LH34T', 'Item Name': '3/4T come along', 'Quantity': 1, 'Category': 'Rigging'},
    {'Item Number': 'RG CC 38-4', 'Item Name': '3/8"x4\' Choker', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG GRN 6FT', 'Item Name': 'Green 6\'', 'Quantity': 1, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 5-8', 'Item Name': 'Shackles 5/8"', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 7-8', 'Item Name': 'Shackles 7/8"', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG YLLW 10FT', 'Item Name': 'Yellow 10\'', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'S 77-1001', 'Item Name': 'Caution tape', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'PPE WM801000', 'Item Name': 'Clear Face shield', 'Quantity': 5, 'Category': 'Saftey'},
    {'Item Number': 'S 77-1004', 'Item Name': 'Danger tape', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'PPE WM858150', 'Item Name': 'Dark Face shield', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'PPE 6800', 'Item Name': 'Ear plugs', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'W SPEEDY-LOOP M5000', 'Item Name': 'Halo', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'PPE 01705A', 'Item Name': 'Harness', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'PPE 4110S', 'Item Name': 'In/Out glasses', 'Quantity': 12, 'Category': 'Saftey'},
    {'Item Number': 'PPE 3200BS L', 'Item Name': 'Large gloves', 'Quantity': 12, 'Category': 'Saftey'},
    {'Item Number': 'S A1107BLUKD', 'Item Name': 'Locks with key', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'PPE 3200BS M', 'Item Name': 'Medium gloves', 'Quantity': 12, 'Category': 'Saftey'},
    {'Item Number': 'PPE 01298', 'Item Name': 'SRL Lanyard', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'PPE 6691UL', 'Item Name': 'Safety Vet', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'S 782796', 'Item Name': 'Water', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'S 30FT YOYO', 'Item Name': 'YoYos', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'HT 13P 1/2 SKT', 'Item Name': '1/2" drive socket set', 'Quantity': 2, 'Category': 'Sockets'},
    {'Item Number': 'HT 21P 3/8 SKT', 'Item Name': '3/8" drive socket set (standard and metric)', 'Quantity': 1, 'Category': 'Sockets'},
    {'Item Number': 'S TAR128', 'Item Name': 'Barricade tag', 'Quantity': 12, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 20TON BTL JCK', 'Item Name': 'Bottle Jack', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'PT KFD29J-PC', 'Item Name': 'Drill Index', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 1528195', 'Item Name': 'Duct Tape', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'S 22CN05', 'Item Name': 'Lock out tag', 'Quantity': 12, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 5P PLR SET', 'Item Name': 'Plier set', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 61044', 'Item Name': 'Punch and Chisel set', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 12P SCRW DR', 'Item Name': 'Screw driver set', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 05337', 'Item Name': 'Tie Wire', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'FL 1673', 'Item Name': 'WD-40', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'C ACET REG', 'Item Name': 'Acetylene Regulator', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 8032014', 'Item Name': 'Acetylene in use saftey cap', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C CMPLT TRCH', 'Item Name': 'Complete Torch', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 0330-0006', 'Item Name': 'Cutting tip #2', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 1-4x50 TRCH HOSE', 'Item Name': 'Oxyen/Acetylene hose 50\'', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C OXY REG', 'Item Name': 'Oxygen Regulator', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 8032010', 'Item Name': 'Oxygen in use safety cap', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C WM4501', 'Item Name': 'Strikers', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'W 1-8 7018', 'Item Name': '7018 1/8"', 'Quantity': 10, 'Category': 'Welding'},
    {'Item Number': 'W WM600416', 'Item Name': 'Carbon wire brush', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'W WLDNG GRND', 'Item Name': 'Ground Clamp', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'FT FL5', 'Item Name': 'Soap stone', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'W WLDNG STNGR', 'Item Name': 'Stingers', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'W WLDNG LD 50FT', 'Item Name': 'Welding Lead', 'Quantity': 2, 'Category': 'Welding'},
    {'Item Number': 'HT 10IN CRSNT WR', 'Item Name': 'Crescent wrench 10"', 'Quantity': 1, 'Category': 'Wrenches'},
    {'Item Number': 'HT 8IN CRSNT WR', 'Item Name': 'Crescent wrench 8"', 'Quantity': 1, 'Category': 'Wrenches'},
    {'Item Number': 'HT 14PC END WR', 'Item Name': 'End wrench sets', 'Quantity': 2, 'Category': 'Wrenches'},
]


utility_trailer_list = [
    {'Item Number': 'HT fldng mtrc hx st', 'Item Name': 'Allen Wrench Set Metric', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'HT fldng sae hx st', 'Item Name': 'Allen Wrench Set Standard', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 14pc end wr', 'Item Name': 'Combination wrench set up to 1-1/4"', 'Quantity': 1, 'Category': 'Wrenches'},
    {'Item Number': 'HT 8in crsnt wr', 'Item Name': 'Crescent wrench 8"', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'HT 10in crsnt wr', 'Item Name': 'Crescent wrench 10"', 'Quantity': 1, 'Category': 'Tool_Box'},
    {'Item Number': 'C 1-4x50 TRCH HOSE', 'Item Name': "Oxyen/Acetylene hose 50'", 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C ACET REG', 'Item Name': 'Acetylene Regulator', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C OXY REG', 'Item Name': 'Oxygen Regulator', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 8032010', 'Item Name': 'Oxygen in use safety cap', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 8032014', 'Item Name': 'Acetylene in use saftey cap', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C RS BUD', 'Item Name': 'Rosebud', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C wm650', 'Item Name': 'Tip Cleaner', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C wm4501', 'Item Name': 'Strikers', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C CMPLT TRCH', 'Item Name': 'Complete Torch', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 0330-0005', 'Item Name': 'Cutting tip #1', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'C 0330-0002', 'Item Name': 'Cutting tip #3', 'Quantity': 1, 'Category': 'Torch/Cutting'},
    {'Item Number': 'EL 04-00105', 'Item Name': '3-way GFCI', 'Quantity': 1, 'Category': 'Electrical'},
    {'Item Number': 'EL 74050PK2V2', 'Item Name': "Extension cord 50'", 'Quantity': 4, 'Category': 'Electrical'},
    {'Item Number': 'EL 542 246', 'Item Name': 'Drop Lights', 'Quantity': 1, 'Category': 'Electrical'},
    {'Item Number': 'FT 410P', 'Item Name': '10" C-Clamps', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT UM125', 'Item Name': '12" L-Clamp', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'F CBY CLMP', 'Item Name': 'Cowboy Clamp', 'Quantity': 2, 'Category': 'Fitting'},
    {'Item Number': 'FT 7168', 'Item Name': 'Sleaver Bar', 'Quantity': 2, 'Category': 'Fitting'},
    {'Item Number': 'FT 75.24', 'Item Name': '2ft Level', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 47-140', 'Item Name': 'Chalk box with string', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 0905', 'Item Name': 'Plumb bob', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'Ft Strng ln', 'Item Name': 'String for plumb bob', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT al tri sq', 'Item Name': 'Speed Square', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 1110', 'Item Name': 'Framing Square', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 7526', 'Item Name': "Tape measure 25'", 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FT 81-9', 'Item Name': 'Torpedo level', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'GC 76318', 'Item Name': 'Flapper Wheels', 'Quantity': 10, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC R4K58', 'Item Name': '4" wire wheel', 'Quantity': 5, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC 22047', 'Item Name': '6" cutting disc', 'Quantity': 50, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'GC 20160', 'Item Name': '4.5" Grinding disc', 'Quantity': 10, 'Category': 'Grinding_Consumables'},
    {'Item Number': 'HT WH-30', 'Item Name': 'Chipping Hammer', 'Quantity': 1, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT 1000 300 224', 'Item Name': 'Claw Hammer', 'Quantity': 1, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT 4LB', 'Item Name': '4lb Hammer', 'Quantity': 1, 'Category': 'Hammer_Rack'},
    {'Item Number': 'HT 10LB', 'Item Name': '10lb Hammer', 'Quantity': 1, 'Category': 'Hammer_Rack'},
    {'Item Number': 'S AFRAME 8FT', 'Item Name': '6ft ladder', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'PT KFD29J-PC', 'Item Name': 'Drill Index', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'HT 5P PLR SET', 'Item Name': 'Plier set', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'HT 61044', 'Item Name': 'Punch and Chisel set', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'HT 12P SCRW DR', 'Item Name': 'Screw driver set', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'FL 1673', 'Item Name': 'WD-40', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'HT 20TON BTL JCK', 'Item Name': 'Bottle Jack', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'HT 05337', 'Item Name': 'Tie Wire', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'PPE WM801000', 'Item Name': 'Clear Face shield', 'Quantity': 5, 'Category': 'Saftey'},
    {'Item Number': 'PPE WM858150', 'Item Name': 'Dark Face shield', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'PPE 4110S', 'Item Name': 'In/Out glasses', 'Quantity': 12, 'Category': 'Saftey'},
    {'Item Number': 'PPE 3200BS M', 'Item Name': 'Medium gloves', 'Quantity': 12, 'Category': 'Saftey'},
    {'Item Number': 'PPE 3200BS L', 'Item Name': 'Large gloves', 'Quantity': 12, 'Category': 'Saftey'},
    {'Item Number': 'PPE 6800', 'Item Name': 'Ear plugs', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'W SPEEDY-LOOP M5000', 'Item Name': 'Halo', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'PPE 6691UL', 'Item Name': 'Safety Vest Large/XL', 'Quantity': 4, 'Category': 'Saftey'},
    {'Item Number': 'PPE SRL LNYRD', 'Item Name': 'SRL Lanyard', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'PPE 01705A', 'Item Name': 'Harness', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'S 30FT YOYO', 'Item Name': 'YoYos', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'HT 14IN PIPE WR', 'Item Name': 'Pipe Wrench 14"', 'Quantity': 1, 'Category': 'Fitting'},
    {'Item Number': 'PT DW511', 'Item Name': '1/2" Drill', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT 1-2IMPACT', 'Item Name': '1/2" Impact', 'Quantity': 2, 'Category': 'Power_Tools'},
    {'Item Number': 'PT HMMRDRLL SDSMAX', 'Item Name': 'SDS max hammer drill', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'PT DWE402', 'Item Name': '4.5" grinder', 'Quantity': 2, 'Category': 'Power_Tools'},
    {'Item Number': 'PT WEP 15-150', 'Item Name': '6" grinder', 'Quantity': 2, 'Category': 'Power_Tools'},
    {'Item Number': 'PT 48 00 5093', 'Item Name': 'Sawzall blades PKG', 'Quantity': 1, 'Category': 'Power_Tools'},
    {'Item Number': 'RG LH34T', 'Item Name': '3/4T come along', 'Quantity': 1, 'Category': 'Rigging'},
    {'Item Number': 'RG CF1T', 'Item Name': '1T Chain Fall', 'Quantity': 1, 'Category': 'Rigging'},
    {'Item Number': 'RG CC 38-4', 'Item Name': '3/8"x4\' Choker', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 5-8', 'Item Name': 'Shackles 5/8"', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG SHCKL 7-8', 'Item Name': 'Shackles 7/8"', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG YLLW 10FT', 'Item Name': "Yellow 10'", 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG GRN 6FT', 'Item Name': "Green 6'", 'Quantity': 1, 'Category': 'Rigging'},
    {'Item Number': 'RG STRP 2-4', 'Item Name': '2x4 flat strap', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'RG STRP 1-4', 'Item Name': '1x4 flat strap', 'Quantity': 2, 'Category': 'Rigging'},
    {'Item Number': 'S 77-1001', 'Item Name': 'Caution tape', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'S 77-1004', 'Item Name': 'Danger tape', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'S A1107BLUKD', 'Item Name': 'Locks', 'Quantity': 6, 'Category': 'Saftey'},
    {'Item Number': 'S 782796', 'Item Name': 'Water', 'Quantity': 2, 'Category': 'Saftey'},
    {'Item Number': 'HT 1528195', 'Item Name': 'Duct Tape', 'Quantity': 1, 'Category': 'Saftey'},
    {'Item Number': 'S 22CN05', 'Item Name': 'Lock out tag', 'Quantity': 12, 'Category': 'Saftey'},
    {'Item Number': 'S TAR128', 'Item Name': 'Barricade tag', 'Quantity': 12, 'Category': 'Saftey'},
    {'Item Number': 'HT 13P 1/2 SKT', 'Item Name': '1/2" drive socket set', 'Quantity': 1, 'Category': 'Sockets'},
    {'Item Number': 'HT 21P 3/8 SKT', 'Item Name': '3/8" drive socket set (standard and metric)', 'Quantity': 1, 'Category': 'Sockets'},
    {'Item Number': 'W WLDNG LD 50FT', 'Item Name': 'Welding Lead', 'Quantity': 5, 'Category': 'Welding'},
    {'Item Number': 'W WLDNG STNGR', 'Item Name': 'Stingers', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'W WLDNG GRND', 'Item Name': 'Ground Clamp', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'W 1-8 7018', 'Item Name': '7018 1/8"', 'Quantity': '10lbs', 'Category': 'Welding'},
    {'Item Number': 'W WM600416', 'Item Name': 'Carbon wire brush', 'Quantity': 1, 'Category': 'Welding'},
    {'Item Number': 'FT FL5', 'Item Name': 'Soap stone', 'Quantity': 1, 'Category': 'Welding'},
]


# Make sure these variables exist and are lists of dicts with the exact keys:
# 'Item Number', 'Item Name', 'Quantity', 'Category'
# standard_trailer_tools = [...]
# semi_trailer_list = [...]
# gang_box_list = [...]
# utility_trailer_list = [...]

# Build the mapping to lists (raw)
tooling_lists = {
    "Standard Trailer":  standard_trailer_tools,
    "Semi":              semi_trailer_list,
    "Semi Trailer":      semi_trailer_list,    # alias
    "Gang Box":          gang_box_list,
    "Utility Trailer":   utility_trailer_list,
    "Tool Trailer":      utility_trailer_list  # legacy alias
}

# Normalize once at import so everyone gets clean integer quantities
tooling_lists = {name: _normalize_tooling_list(items, name) for name, items in tooling_lists.items()}

def get_tooling_list(name: str):
    key = (name or "").strip()
    return tooling_lists.get(key, [])

